// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlRqnsjWKvFjixQnSdKGy1pPWtqPU6_zw',
    appId: '1:88983325238:web:de7b37a5e7170e0f94e697',
    messagingSenderId: '88983325238',
    projectId: 'doan-49978',
    authDomain: 'doan-49978.firebaseapp.com',
    storageBucket: 'doan-49978.firebasestorage.app',
    measurementId: 'G-6BN5XM95WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL8qZuOLzAZsoyxFnBwQGUhf7HOb1DydM',
    appId: '1:88983325238:android:f46df3359d1a853b94e697',
    messagingSenderId: '88983325238',
    projectId: 'doan-49978',
    storageBucket: 'doan-49978.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADG83g1Iz-OApGzf8gnySe-fHJbHdUPr4',
    appId: '1:88983325238:ios:48489d4cc14248af94e697',
    messagingSenderId: '88983325238',
    projectId: 'doan-49978',
    storageBucket: 'doan-49978.firebasestorage.app',
    androidClientId: '88983325238-3eivcmlmg5f8qmubcjb7tkenfgbm6to6.apps.googleusercontent.com',
    iosClientId: '88983325238-9v1nc9qvpg75c7389get9j1d6gduu3r7.apps.googleusercontent.com',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADG83g1Iz-OApGzf8gnySe-fHJbHdUPr4',
    appId: '1:88983325238:ios:1277b79dd990243a94e697',
    messagingSenderId: '88983325238',
    projectId: 'doan-49978',
    storageBucket: 'doan-49978.firebasestorage.app',
    androidClientId: '88983325238-3eivcmlmg5f8qmubcjb7tkenfgbm6to6.apps.googleusercontent.com',
    iosClientId: '88983325238-ro8eibfotl70fkv2vn6f3lari33ginuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlRqnsjWKvFjixQnSdKGy1pPWtqPU6_zw',
    appId: '1:88983325238:web:de03b6e4f558b31294e697',
    messagingSenderId: '88983325238',
    projectId: 'doan-49978',
    authDomain: 'doan-49978.firebaseapp.com',
    storageBucket: 'doan-49978.firebasestorage.app',
    measurementId: 'G-YSP8QVP0QY',
  );
}
